#!/usr/bin/env bash
set -euo pipefail

echo "MCPNest CLI - Publishing Guide"
echo "=============================="
echo ""
echo "This tool is now ready for distribution!"
echo ""
echo "## Local Testing:"
echo "1. Test locally with npm link:"
echo "   npm link"
echo "   mcpnest --help"
echo ""
echo "2. Test with npx (after publishing):"
echo "   npx mcpnest-cli --help"
echo ""
echo "## Publishing to npm:"
echo "1. Update package.json:"
echo "   - Set your author name"
echo "   - Update repository URL"
echo "   - Update version if needed"
echo ""
echo "2. Login to npm:"
echo "   npm login"
echo ""
echo "3. Publish package:"
echo "   npm publish"
echo ""
echo "## Usage after publishing:"
echo "Global install:  npm i -g mcpnest-cli"
echo "Using npx:       npx mcpnest-cli read"
echo ""
echo "Current package info:"
echo "====================="
npm pack --dry-run | grep -E "^(name|version|files included|total files|unpacked size)"